### PR TITLE
letsencrypt: update certbot-dns-multi to 4.33.0, add dns_multi_nameservers option for split DNS setups

### LINKED ISSUE #4442: Let's encrypt cloudflare token challenge fails to find zone
### Describe the issue you are experiencing

Lets encrypt fails to find the zone, despite having the right token and have tested the setup aside from this addon with certbot.

Enabled verbose mode

I've verified the token works correctly, but there's something wrong

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which app are you reporting an issue with?

Let's Encrypt

### What is the version of the app?

6.0.4

### Steps to reproduce the issue

1. setup cloudflare token, restricted to zone read and dns edit
2. add token to addon configuration
3. observe failure

## System Information

version | core-2026.2.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
container_arch | aarch64
user | root
virtualenv | false
python_version | 3.13.11
os_name | Linux
os_version | 6.18.5-current-rockchip64
arch | aarch64
timezone | Europe/London
config_dir | /config

### Anything in the Supervisor logs that might be useful for us?

```txt

```

### Anything in the app logs that might be useful for us?

```txt
Storing nonce: <nonce>
Performing the following challenges:
dns-01 challenge for some.domain.xyz
Configuring lego for provider cloudflare with 3 options
Asking lego to create record <record> for domain some.domain.xyz
Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 90, in perform
    LegoClient.present(
    ~~~~~~~~~~~~~~~~~~^
        achall.domain,
        ^^^^^^^^^^^^^^
        encode_b64jose(achall.token),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        achall.key_authorization(achall.account_key),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 161, in present
    LegoClient._raise_for_response(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        cmd(
        ^^^^
    ...<8 lines>...
        )
        ^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 193, in _raise_for_response
    raise errors.PluginError(resp["error"])
certbot.errors.PluginError: cloudflare: failed to find zone xyz.: zone could not be found
Calling registered functions
Cleaning up challenges
Asking lego to clean up record <record> for domain some.domain.xyz
Cleanup of some.domain.xyz failed: cloudflare: failed to find zone xyz.: zone could not be found
Cleanup error was
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 90, in perform
    LegoClient.present(
    ~~~~~~~~~~~~~~~~~~^
        achall.domain,
        ^^^^^^^^^^^^^^
        encode_b64jose(achall.token),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        achall.key_authorization(achall.account_key),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 161, in present
    LegoClient._raise_for_response(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        cmd(
        ^^^^
    ...<8 lines>...
        )
        ^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 193, in _raise_for_response
    raise errors.PluginError(resp["error"])
certbot.errors.PluginError: cloudflare: failed to find zone xyz.: zone could not be found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 116, in cleanup
    LegoClient.cleanup(
    ~~~~~~~~~~~~~~~~~~^
        achall.domain,
        ^^^^^^^^^^^^^^
        encode_b64jose(achall.token),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        achall.key_authorization(achall.account_key),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 176, in cleanup
    LegoClient._raise_for_response(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        cmd(
        ^^^^
    ...<8 lines>...
        )
        ^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 193, in _raise_for_response
    raise errors.PluginError(resp["error"])
certbot.errors.PluginError: cloudflare: failed to find zone xyz.: zone could not be found
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/main.py", line 1871, in main
    return config.func(config, plugins)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/main.py", line 1577, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/client.py", line 513, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/client.py", line 423, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/client.py", line 492, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/local/lib/python3.13/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 90, in perform
    LegoClient.present(
    ~~~~~~~~~~~~~~~~~~^
        achall.domain,
        ^^^^^^^^^^^^^^
        encode_b64jose(achall.token),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        achall.key_authorization(achall.account_key),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 161, in present
    LegoClient._raise_for_response(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        cmd(
        ^^^^
    ...<8 lines>...
        )
        ^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/certbot_dns_multi/_internal/dns_multi.py", line 193, in _raise_for_response
    raise errors.PluginError(resp["error"])
certbot.errors.PluginError: cloudflare: failed to find zone xyz.: zone could not be found
cloudflare: failed to find zone xyz.: zone could not be found
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by artbird309**
Fixes #4442

certbot-dns-multi 4.33.0 adds the `--dns-multi-nameservers` flag, which overrides
the resolvers used for SOA zone determination and CNAME resolution. This PR bumps
the pinned version and wires up a new `dns_multi_nameservers` config option that
passes the flag through to certbot.

This fixes cert renewal in split DNS setups where local DNS returns a different SOA
than the public authoritative server, causing lego to identify the wrong zone and
fail the Cloudflare (or other provider) API lookup with
`failed to find zone <domain>: zone could not be found`.

The `--dns-multi-nameservers` support was contributed to certbot-dns-multi upstream
and released in 4.33.0: https://github.com/alexzorin/certbot-dns-multi/pull/24

Tested using the devcontainer against a real split DNS setup (AdGuard + Windows DNS)
with Cloudflare as the DNS provider. Confirmed failure without the option and
successful cert issuance with `dns_multi_nameservers: '1.1.1.1'`.

---
This PR was developed with assistance from Claude Sonnet 4.6 (Anthropic).

## Summary by CodeRabbit

* **New Features**
  * Added dns_multi_nameservers option to specify custom DNS servers (comma-separated, optional, supports optional port) for split-DNS/zone resolution.

* **Documentation**
  * Added guide on split DNS and custom nameserver usage with examples and guidance for SOA mismatch scenarios.

* **Chores**
  * Bumped addon version to 6.3.0.
  * Updated certbot-dns-multi to 4.33.0.

### CODE REVIEW

File: letsencrypt/rootfs/etc/services.d/lets-encrypt/run [hunk 1]
```diff
@@ -44,6 +44,11 @@ if [ "${CHALLENGE}" == "dns" ]; then
     fi
     bashio::log.info "Use propagation seconds: ${PROPAGATION_SECONDS}"
 
+    DNS_MULTI_NAMESERVERS=""
+    if bashio::config.has_value 'dns.dns_multi_nameservers'; then
+        DNS_MULTI_NAMESERVERS="$(bashio::config 'dns.dns_multi_nameservers')"
+    fi
+
```
Comment (sairon) [inline letsencrypt/rootfs/etc/services.d/lets-encrypt/run]:
```suggestion
```

File: letsencrypt/rootfs/etc/services.d/lets-encrypt/run [hunk 2]
```diff
@@ -547,6 +552,9 @@ if [ "${CHALLENGE}" == "dns" ]; then
         echo "${PROVIDER_ENV_PREFIX}_PROPAGATION_TIMEOUT=${PROPAGATION_SECONDS}" >> "${DNS_MULTI_CREDS}"
 
         ACME_ARGUMENTS+=("--authenticator" "dns-multi" "--dns-multi-credentials" "${DNS_MULTI_CREDS}" "--dns-multi-propagation-seconds" "${PROPAGATION_SECONDS}")
+        if [ -n "${DNS_MULTI_NAMESERVERS}" ]; then
+            ACME_ARGUMENTS+=("--dns-multi-nameservers" "${DNS_MULTI_NAMESERVERS}")
+        fi
```
Comment (sairon) [inline letsencrypt/rootfs/etc/services.d/lets-encrypt/run]:
```suggestion
        if bashio::config.has_value 'dns.dns_multi_nameservers'; then
            ACME_ARGUMENTS+=("--dns-multi-nameservers" "$(bashio::config 'dns.dns_multi_nameservers')")
        fi
```
