### PR TITLE
mosquitto: 6.0.0

### LINKED ISSUE #729: Update mosquitto add-on to use Bashio
The add-ons now have [Bashio](https://github.com/hassio-addons/bashio) available, which makes it easier and nicer to work with and is easier to understand. The `mosquitto` add-on needs to be rewritten to use the Bashio functions.

In general, this only requires changes to the add-on [`run.sh`](https://github.com/home-assistant/hassio-addons/blob/master/mosquitto/data/run.sh) script. A good example of an add-on that has been migrated already, is [`deconz`](https://github.com/home-assistant/hassio-addons/blob/master/deconz/data/run.sh).

Please note, nothing has to be done to make Bashio available, it is already baked-in into the add-on base images.

### LINKED ISSUE #1747: Mqtt official broker problems with ESP sending messages ?
## The problem
 From maybe 2018, since I start using hassio, many/many sd card ago... :D I had allways some collapse ... and consequence sd card getting corrupted...  sometime it survived 3-4 weeks... not good enough.  The card get corrupted, because at the distance, I make an off/on with an switch remote from tuya... normally nothing happens, all went well... sometimes corruption...

Several times I thought I was getting hacked or something... but this happens even without connection with the outside... none whatsoever... mosquitto getting of the line, not doing anything ... not doing the work of broker... that is.

## Environment

I use the ESP 8266 coded with the normal libraries to connect to the mqtt broker of hassio the mosquitto one... to send the data from my arduino (connected via serial with an arduino)... and zigbee2mqtt on top, I had many weeks of good service... though... this mqtt broker never was stable enough. several times it survived weeks... sometimes just hours.

Then, just a few days ago, Again...I even had to the change the sdd card.... again... and said... enough... 1 terabit hard disc to the raspberry with a nicely 5 amp power source... with an usb extension charged from outside...

The MQTT disconnects from everything, don't restart (zigbee doesn't do anything anymore it needs the broker)... but the hassio enviroment, works nicely. 

could be the ESP connected  though the mqtt that works bad? (ite sends some weird stuff to the broker that makes him... sleep?!?) inconsistent? not every time, but sometimes...
 it's weird that it's only me?

I never was able to put more than 30 zigbee sensors (I have a lot more mind you not only zigbee or mqtt... the system after 2-3 weeks get corrupted, and I had to do an fresh resinstall... I was lasy to make an copy of this... my system never progressed like I wanted. But now it's a lot more "consistent" (with the failures)... I even was able to replicate this with an i386 machine with hassio (virtual machine with 8 gigas of ram ...more than the riny raspberry)
- Add-on with the issue: **MQTT official broker**
- Add-on release with the issue: **Every single one ... worse now...** (maybe because of more stuff on my side)
- Last working add-on release (if known): **I believe this never worked ok...** it's just worse when I put more stuff.
- Operating environment (OS/Supervised): hassio for i386 and hassio for the rasppberry pi3

## Problem-relevant configuration
 When I put  just the mosquitto in there with receving both zigbee2mqtt and the esp messages ( I don't believe it's the zigbee2mqtt... but my ESP...

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  server_port: xxxxx
octoprint:
  host: xxxxxx
  api_key: xxxxx
mqtt:
  discovery: true
  discovery_prefix: homeassistant
sensor:  
  - platform: mqtt
    name: "Temperature sump"
    state_topic: "sensor/Temperatura Sump"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Humidade sump"
    state_topic: "sensor/Humidade sump"
    unit_of_measurement: '%'
    icon: mdi:water-percent
  - platform: mqtt
    name: "Temperatura água"
    state_topic: "sensor/Temperatura água"
    unit_of_measurement: '°C'
    icon: mdi:coolant-temperature
  - platform: mqtt
    name: "Condutividade água osmose"
    state_topic: "sensor/tdsValue"
    unit_of_measurement: '°'
    icon: mdi:water
  - platform: mqtt
    name: "Estado"
    state_topic: "sensor/estado"
  - platform: mqtt
    name: "Potência Violeta"
    state_topic: "sensor/Potência luz"
    unit_of_measurement: '%'
  - platform: mqtt
    name: "Potência Branco"
    state_topic: "sensor/Potência luz2"
    unit_of_measurement: '%'
  - platform: mqtt
    name: "Potência Azul"    
    state_topic: "sensor/Potência luz3"
    unit_of_measurement: '%'
  - platform: mqtt
    name: "Horas"
    state_topic: "sensor/Horas"
  - platform: mqtt
    name: "Minutos"
    state_topic: "sensor/Minutos"
  - platform: mqtt
    name: "Segundos"    
    state_topic: "sensor/Segundos"
  - platform: mqtt
    name: "Bomba de reposição"
    state_topic: "sensor/Bomba de reposição"
  - platform: mqtt
    name: "Frasco escumador"    
    state_topic: "sensor/frasco escumador"
  - platform: mqtt
    name: "pH água"    
    state_topic: "sensor/pH água"
    unit_of_measurement: 'º'
    icon: mdi:test-tube
  - platform: enphase_envoy
    name: enphase_new
#     username: xxxxxx
#     password: xxxx
    ip_address: xxxxxxx
    scan_interval: 30
    monitored_conditions:
      - production
      - consumption
      - daily_production
      - seven_days_production
      - lifetime_production
      - inverters
      # Calculate Remaining Power
  - platform: template
    sensors:
      remaining_power:
        value_template: >
          {{ '%0.1f' | format(states('sensor.enphase_newenvoy_current_energy_consumption') | float - 
                              states('sensor.enphase_newenvoy_current_energy_production') | float) }}
        unit_of_measurement: 'W'
        friendly_name: Energia importada
switch:
  - platform: mqtt
    name: "Tasmota"
    state_topic: "stat/tasmota/RESULT"  
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/tasmota/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "tele/tasmota/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
```

## Traceback/Error logs

```txt

```

## Additional information

And then I start using the mqtt that you are going to remove from the add-on ... the mqtt server and web client addon... everything FINE ok, just after 2-3 days... (fingers crossed) but after I gained courage to put the mosquitto... all went... bad again! So it's the mosquito, and if I am one of the few, I bet something from the ESP, that this mosquito doesnt't like... I could put also the code of the esp for you to see... this is really weird... why the other mqtt server works nicely... I don't really now...

I have an similar post that Frenk closed, but I was on wrong assumptions... now I tested it a lot more... My idea is that with this "old" mqtt broker, I will never  be bad... if you erased this... I might have to go to the non hassio enviroment... to get an mqtt that works...

### LINKED ISSUE #1765: MQTT User?
## The problem
What to do with MQTT User?

Documentation Page says:
_Create a new user for MQTT via the Configuration -> Users (manage users). Notes:

This name cannot be homeassistant or addon, those are reserved usernames.
If you do not see the option to create a new user, ensure that Advanced Mode is enabled in your profile._

But I fail to see what is to be done with this created user?

## Environment

- Add-on with the issue: MQTT
- Add-on release with the issue:  Current version: 5.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS 5.10/core-2021.1.3/supervisor-2021.01.4

## Problem-relevant configuration

```yaml
logins: []
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.68.0/24
        - fd00::/8
        - 127.0.0.1
    - type: homeassistant

```

## Traceback/Error logs

```txt
1610790452: Socket error on client <unknown>, disconnecting.
1610790467: New connection from 172.30.32.1 on port 1883.
1610790467: Socket error on client <unknown>, disconnecting.
```

### LINKED ISSUE #1774: Reopen Issue #1329
## The problem

Stale Bot closes the issue #1329
There are still multiple Users with this issue!

Please open it again

## Environment
Mosquitto Addon

## Problem-relevant configuration
See #1329

## Traceback/Error logs
See #1329

### LINKED ISSUE #1817: Mosquitto is unreliable, requires multiple restarts to work, devices unavailable
## The problem
When restarting HA, multiple if not all mqtt devices are unavailable, multiple restarts of MQTT broker addon and integration are required

## Environment

- Add-on with the issue: mosquitto
- Add-on release with the issue:  5.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  HASS.IO supervised

## Problem-relevant configuration

```yaml

```
No manual config, everything done via UI

## Traceback/Error logs

```txt
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 233
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 234
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 235
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 236
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 237
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 238
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 239
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 240
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 241
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 242
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 243
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 244
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 245
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 246
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 247
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 248
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 249
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 250
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 251
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 252
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 253
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 254
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 255
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 256
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 257
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 258
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 259
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 260
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 261
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 262
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 263
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 264
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 265
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 266
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 267
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 268
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 269
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 270
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 271
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 272
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 273
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 274
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 275
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 276
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 277
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 278
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 279
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 280
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 281
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 282
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 283
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 284
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 285
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 286
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 287
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 288
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 289
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 290
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 291
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 292
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 293
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 294
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 295
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 296
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 297
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 298
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 299
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 300
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 301
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 302
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 303
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 304
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 305
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 306
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 307
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 308
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 309
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 310
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 311
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 312
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 313
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 314
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 315
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 316
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 317
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 318
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 319
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 320
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 321
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 322
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 323
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 324
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 325
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 326
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 327
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 328
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 329
2021-02-07 09:04:05 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 330
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 331
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 332
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 333
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 334
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 335
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 336
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 337
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 338
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 339
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 340
2021-02-07 09:04:06 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 341
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 342
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 343
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 344
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 345
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 346
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 347
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 348
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 349
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 350
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 351
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 352
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 353
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 354
2021-02-07 09:04:07 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 355
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 356
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 357
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 358
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 359
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 360
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 361
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 362
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 363
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 364
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 365
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 366
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 367
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 368
2021-02-07 09:04:08 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 369
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 370
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 371
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 372
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 373
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 374
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 375
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 376
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 377
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 378
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 379
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 380
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 381
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 382
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 383
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 384
2021-02-07 09:04:09 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 385
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 386
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 387
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 388
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 389
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 390
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 391
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 392
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 393
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 394
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 395
2021-02-07 09:04:10 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 396
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 397
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 398
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 399
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 400
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 401
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 402
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 403
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 404
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 405
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 406
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 407
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 408
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 409
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 410
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 411
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 412
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 413
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 414
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 415
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 416
2021-02-07 09:04:11 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 417
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 418
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 419
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 420
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 421
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 422
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 423
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 424
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 425
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 426
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 427
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 428
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 429
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 430
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 431
2021-02-07 09:04:12 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 432
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 433
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 434
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 435
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 436
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 437
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 438
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 439
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 440
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 441
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 442
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 443
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 444
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 445
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 446
2021-02-07 09:04:13 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 447
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 448
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 449
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 450
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 451
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 452
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 453
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 454
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 455
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 456
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 457
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 458
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 459
2021-02-07 09:04:14 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 460
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 461
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 462
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 463
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 464
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 465
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 466
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 467
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 468
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 469
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 470
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 471
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 472
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 473
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 474
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 475
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 476
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 477
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 478
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 479
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 480
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 481
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 482
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 483
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 484
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 485
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 486
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 487
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 488
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 489
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 490
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 491
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 492
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 493
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 494
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 495
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 496
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 497
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 498
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 499
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 500
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 501
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 502
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 503
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 504
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 505
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 506
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 507
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 508
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 509
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 510
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 511
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 512
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 513
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 514
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 515
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 516
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 517
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 518
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 519
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 520
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 521
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 522
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 523
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 524
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 525
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 526
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 527
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 528
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 529
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 530
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 531
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 532
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 533
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 534
2021-02-07 09:04:15 ERROR (MainThread) [homeassistant.components.mqtt] Timed out waiting for mid 535
```

## Additional information

only thing in the logs are the time out, i'm spammed

### LINKED ISSUE #1887: Mosquitto 5.1.1 is broken.
## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): 5.1
- Operating environment (OS/Supervised): hassio

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

### LINKED ISSUE #1897: Mosquitto is leaking memory
## The problem
It seems mosquitto is leaking memory on my system. After a few days, it has reached to 6 GB (the allocated memory to the VM) and the instance is killed by the oom-killer.

I did notice that the mosquitto addon is using an rather old version of mosquitto, and since then, a few memory-leaks have been fixed. See https://github.com/eclipse/mosquitto/blob/master/ChangeLog.txt

I do find it strange that I seem to be the only user impacted, since I can't find anything on the forums or somewhere else. I'm not sure on how to proceed to troubleshoot this. Is there a way to query mosquitto to know why it consumes so much memory? I'm thinking that it may be keeping retained messages in memory, but I don't see how it can reach to 6GB in a few days.

The container log only talks about writing the in-memory database to a file:
```
1614754585: Saving in-memory database to /data/mosquitto.db.
1614756386: Saving in-memory database to /data/mosquitto.db.
1614758187: Saving in-memory database to /data/mosquitto.db.
1614759988: Saving in-memory database to /data/mosquitto.db.
```

That file isn't large at all:

```
/ # ls -lah /data/mosquitto.db
-rw-------    1 root     root       51.8K Mar  3 09:26 /data/mosquitto.db
```

After two hours of uptime it's using about 140MB of memory.
```
# ps aux | grep mosquitto
  245 root      0:16 mosquitto -c /etc/mosquitto.conf
 4093 root      0:00 grep mosquitto
# cat /proc/245/status
Name:	mosquitto
Umask:	0022
State:	S (sleeping)
Tgid:	245
Ngid:	0
Pid:	245
PPid:	187
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	256
Groups:	0 1 2 3 4 6 10 11 20 26 27 
NStgid:	245
NSpid:	245
NSpgid:	187
NSsid:	1
VmPeak:	  141836 kB
VmSize:	  141836 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  140808 kB
VmRSS:	  140808 kB
RssAnon:	  136960 kB
RssFile:	    3848 kB
RssShmem:	       0 kB
VmData:	  136932 kB
VmStk:	     132 kB
VmExe:	     160 kB
VmLib:	    2460 kB
VmPTE:	     312 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	0
Threads:	1
SigQ:	0/23732
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000004a03
SigIgn:	0000000000001004
SigCgt:	0000000000004a03
CapInh:	00000000a80425fb
CapPrm:	00000000a80425fb
CapEff:	00000000a80425fb
CapBnd:	00000000a80425fb
CapAmb:	0000000000000000
NoNewPrivs:	0
Speculation_Store_Bypass:	vulnerable
Cpus_allowed:	f
Cpus_allowed_list:	0-3
Mems_allowed:	00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	235989
nonvoluntary_ctxt_switches:	2981
```

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): Unknown
- Operating environment (OS/Supervised): Home Assistant OS 5.12

## Problem-relevant configuration

```yaml
logins:
  - username: iotlink
    password: xxx
  - username: hass
    password: xxx
  - username: lirc
    password: xxx
  - username: cec
    password: xxx
  - username: garage
    password: xxx
  - username: eltako
    password: xxx
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

dmesg from the host:
```txt
[448576.880624] mosquitto invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[448576.880635] CPU: 0 PID: 3455 Comm: mosquitto Not tainted 5.4.99 #1
[448576.880635] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 0.0.0 02/06/2015
[448576.880638] Call Trace:
[448576.881626]  dump_stack+0x66/0x81
[448576.882132]  dump_header+0x45/0x1da
[448576.882137]  oom_kill_process.cold+0xb/0x10
[448576.882666]  out_of_memory+0x193/0x430
[448576.882685]  __alloc_pages_slowpath+0xb53/0xdb0
[448576.883397]  ? zram_bvec_rw.isra.0+0x120/0x680
[448576.883401]  __alloc_pages_nodemask+0x2c5/0x300
[448576.883632]  alloc_pages_vma+0xc1/0x170
[448576.883937]  do_swap_page+0x341/0x6e0
[448576.883955]  __handle_mm_fault+0x45f/0xc90
[448576.883967]  ? call_function_single_interrupt+0xa/0x20
[448576.883969]  handle_mm_fault+0xbf/0x1f0
[448576.884234]  do_user_addr_fault+0x1c4/0x440
[448576.884240]  async_page_fault+0x34/0x40
[448576.884251] RIP: 0033:0x55c3f84704dc
[448576.884253] Code: e8 99 b4 fe ff 48 8d 6c 24 08 48 89 fa b9 b0 00 00 00 31 c0 48 89 ef 48 8b 5a 48 49 83 cc ff f3 ab 48 85 db 0f 84 46 01 00 00 <44> 8b 7b 3c 45 85 ff 0f 8e 31 01 00 00 4c 8b 73 40 4d 85 f6 0f 84
[448576.884254] RSP: 002b:00007fffe4474e30 EFLAGS: 00010202
[448576.884258] RAX: 0000000000000000 RBX: 000055c488f78f40 RCX: 0000000000000000
[448576.884259] RDX: 0000000000000001 RSI: 00007fffe4474e5e RDI: 000055c56f30733b
[448576.884259] RBP: 00007fffe4474e38 R08: 0000000000000001 R09: 0000000080008000
[448576.884260] R10: 00007f9599109101 R11: 0000000000000206 R12: ffffffffffffffff
[448576.884261] R13: 000055c56f3071c0 R14: 000055c556ce7a80 R15: 0000000000000000
[448576.884287] Mem-Info:
[448576.884293] active_anon:1144252 inactive_anon:218350 isolated_anon:0
                 active_file:609 inactive_file:922 isolated_file:0
                 unevictable:0 dirty:0 writeback:0 unstable:0
                 slab_reclaimable:15036 slab_unreclaimable:20189
                 mapped:1070 shmem:324 pagetables:5870 bounce:0
                 free:13655 free_pcp:1117 free_cma:0
[448576.884296] Node 0 active_anon:4577008kB inactive_anon:873400kB active_file:2436kB inactive_file:3688kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:4280kB dirty:0kB writeback:0kB shmem:1296kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[448576.884297] Node 0 DMA free:14916kB min:24kB low:36kB high:48kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15004kB managed:14916kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[448576.884300] lowmem_reserve[]: 0 2987 5918 5918
[448576.884302] Node 0 DMA32 free:19672kB min:4960kB low:8016kB high:11072kB active_anon:2402892kB inactive_anon:505444kB active_file:1040kB inactive_file:1156kB unevictable:0kB writepending:0kB present:3125440kB managed:3059468kB mlocked:0kB kernel_stack:188kB pagetables:6436kB bounce:0kB free_pcp:2080kB local_pcp:764kB free_cma:0kB
[448576.884305] lowmem_reserve[]: 0 0 2930 2930
[448576.884306] Node 0 Normal free:20032kB min:4868kB low:7868kB high:10868kB active_anon:2174416kB inactive_anon:368484kB active_file:2516kB inactive_file:2784kB unevictable:0kB writepending:0kB present:3145728kB managed:3004964kB mlocked:0kB kernel_stack:9204kB pagetables:17044kB bounce:0kB free_pcp:2304kB local_pcp:1476kB free_cma:0kB
[448576.884309] lowmem_reserve[]: 0 0 0 0
[448576.884310] Node 0 DMA: 1*4kB (E) 0*8kB 0*16kB 2*32kB (E) 2*64kB (E) 1*128kB (E) 1*256kB (E) 0*512kB 2*1024kB (E) 2*2048kB (E) 2*4096kB (E) = 14916kB
[448576.884317] Node 0 DMA32: 964*4kB (UMEH) 973*8kB (UMEH) 324*16kB (UMEH) 30*32kB (UMEH) 15*64kB (EH) 3*128kB (H) 1*256kB (H) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 19384kB
[448576.884323] Node 0 Normal: 3527*4kB (UMEH) 528*8kB (UMEH) 101*16kB (UMEH) 21*32kB (UEH) 2*64kB (H) 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 20748kB
[448576.884330] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[448576.884331] 1928 total pagecache pages
[448576.884332] 11 pages in swap cache
[448576.884333] Swap cache stats: add 18034405, delete 18034283, find 349198/17945010
[448576.884333] Free swap  = 0kB
[448576.884334] Total swap = 1519836kB
[448576.884334] 1571543 pages RAM
[448576.884337] 0 pages HighMem/MovableOnly
[448576.884338] 51706 pages reserved
[448576.884339] Tasks state (memory values in pages):
[448576.884339] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[448576.884348] [    136]     0   136    48771       52   356352      167          -250 systemd-journal
[448576.884350] [    151]     0   151     2935        5    57344      266         -1000 systemd-udevd
[448576.884365] [    296]  1003   296     4568       80    77824      963             0 systemd-resolve
[448576.884367] [    297]  1004   297    58346        0    77824      203             0 systemd-timesyn
[448576.884369] [    300]     0   300     1029        0    45056       24             0 acpid
[448576.884370] [    301]  1001   301     1651        7    53248      287          -900 dbus-daemon
[448576.884372] [    302]     0   302   280049        5   188416      983             0 NetworkManager
[448576.884374] [    307]     0   307    58186        3    77824      256             0 rauc
[448576.884376] [    310]     0   310    75259        0    86016      128             0 rngd
[448576.884387] [    314]     0   314     2614        3    57344      168             0 systemd-logind
[448576.884389] [    315]     0   315     2424       14    57344      121             0 wpa_supplicant
[448576.884390] [    331]     0   331     1995       22    45056       59             0 qemu-ga
[448576.884392] [    345]     0   345   432092     7253   405504     1061          -500 dockerd
[448576.884394] [    352]     0   352   684466     2460   446464      873          -500 containerd
[448576.884396] [    510]     0   510   305479        0   143360      179          -500 docker-proxy
[448576.884398] [    518]     0   518   325690      381   172032      124          -499 containerd-shim
[448576.884400] [    534]     0   534       49        0    28672        6             0 s6-svscan
[448576.884401] [    615]     0   615       49        0    32768        5             0 s6-supervise
[448576.884403] [    677]     0   677      725        0    45056       27             0 dropbear
[448576.884405] [    773]     0   773       49        0    32768        4             0 s6-supervise
[448576.884407] [    777]     0   777   178361        0   102400      607             0 observer
[448576.884409] [    803]     0   803   355169        0   278528     2165             0 docker
[448576.884410] [    804]     0   804      766        4    45056       41             0 agetty
[448576.884412] [    807]     0   807      766        7    49152       40             0 agetty
[448576.884414] [    840]     0   840   325690      497   184320      192          -499 containerd-shim
[448576.884416] [    857]     0   857       49        0    32768        7             0 s6-svscan
[448576.884418] [    932]     0   932       49        0    32768        5             0 s6-supervise
[448576.884420] [   1114]     0  1114       49        0    32768        4             0 s6-supervise
[448576.884421] [   1115]     0  1115       49        0    32768        4             0 s6-supervise
[448576.884423] [   1117]     0  1117     1043        1    53248      523             0 bash
[448576.884434] [   1118]     0  1118    36667        0   323584    12056             0 python3
[448576.884436] [   1420]     0  1420   325626      381   176128      143          -499 containerd-shim
[448576.884438] [   1436]     0  1436       49        0    32768        6             0 s6-svscan
[448576.884440] [   1512]     0  1512       49        0    32768        4             0 s6-supervise
[448576.884442] [   1639]     0  1639   325626      373   172032      134          -499 containerd-shim
[448576.884444] [   1680]     0  1680       49        0    32768        6             0 s6-svscan
[448576.884446] [   1718]     0  1718       49        0    32768        4             0 s6-supervise
[448576.884448] [   1720]     0  1720   180221        0   126976     2447             0 coredns
[448576.884450] [   1804]     0  1804       49        0    32768        3             0 s6-supervise
[448576.884452] [   2009]     0  2009   325626      383   176128      129          -499 containerd-shim
[448576.884454] [   2031]     0  2031       49        0    32768        6             0 s6-svscan
[448576.884456] [   2193]     0  2193       45        0    28672        5             0 foreground
[448576.884458] [   2194]     0  2194       49        0    32768        3             0 s6-supervise
[448576.884468] [   2208]     0  2208       44        0    28672        4             0 foreground
[448576.884470] [   2374]     0  2374      394        0    45056       10             0 sleep
[448576.884472] [   2419]     0  2419   325626      376   176128      134          -499 containerd-shim
[448576.884474] [   2445]     0  2445       49        0    32768        4             0 s6-svscan
[448576.884476] [   2489]     0  2489       49        0    32768        3             0 s6-supervise
[448576.884478] [   2592]     0  2592       49        0    32768        4             0 s6-supervise
[448576.884480] [   2593]     0  2593       49        0    32768        3             0 s6-supervise
[448576.884482] [   2595]     0  2595    23784        0    98304      321             0 pulseaudio
[448576.884484] [   2596]     0  2596     3736        1    61440      435             0 bash
[448576.884486] [   2686]     0  2686     3736        0    61440      430             0 bash
[448576.884488] [   2688]     0  2688     4461        1    77824      151             0 udevadm
[448576.884490] [   2706]     0  2706       49        0    28672        3             0 s6-supervise
[448576.884492] [   2708]     0  2708      209        7    36864        4             0 mdns-repeater
[448576.884494] [   2730]     0  2730     1865       10    49152       72             0 bluetoothd
[448576.884495] [   2762]     0  2762   287110        0   139264      192          -500 docker-proxy
[448576.884497] [   2775]     0  2775   305543        0   147456      168          -500 docker-proxy
[448576.884499] [   2789]     0  2789   305543        0   151552      169          -500 docker-proxy
[448576.884501] [   2803]     0  2803   305959        0   151552      191          -500 docker-proxy
[448576.884502] [   2812]     0  2812   325626      386   167936      125          -499 containerd-shim
[448576.884504] [   2829]     0  2829      249        4    28672        6             0 docker-init
[448576.884506] [   2873]     0  2873       49        0    32768        5             0 s6-svscan
[448576.884508] [   2901]     0  2901       45        0    28672        6             0 foreground
[448576.884509] [   2902]     0  2902       49        0    32768        5             0 s6-supervise
[448576.884511] [   2913]     0  2913       44        0    28672        4             0 foreground
[448576.884513] [   2983]     0  2983   325626      370   176128      147          -499 containerd-shim
[448576.884515] [   3035]     0  3035      249        4    28672        6             0 docker-init
[448576.884516] [   3084]     0  3084     1103        1    49152      608             0 bash
[448576.884518] [   3131]     0  3131       49        0    32768        5             0 s6-svscan
[448576.884520] [   3161]     0  3161       45        0    28672        4             0 foreground
[448576.884522] [   3162]     0  3162       49        0    32768        3             0 s6-supervise
[448576.884524] [   3173]     0  3173       44        0    28672        4             0 foreground
[448576.884526] [   3316]     0  3316     1031        2    45056      513             0 bash
[448576.884528] [   3346]     0  3346   325626      394   172032      126          -499 containerd-shim
[448576.884530] [   3368]     0  3368       49        0    32768        4             0 s6-svscan
[448576.884531] [   3454]     0  3454     1194       10    45056       86             0 socat
[448576.884533] [   3455]     0  3455  1537304  1296282 12357632   239869             0 mosquitto
[448576.884535] [   3496]     0  3496       49        0    32768        3             0 s6-supervise
[448576.884537] [   3649]     0  3649       49        0    32768        3             0 s6-supervise
[448576.884538] [   3652]     0  3652     3706        2    65536      425             0 bash
[448576.884541] [   3686]     0  3686     3557        2    61440      109             0 mysqld_safe
[448576.884543] [   3858]     0  3858   123905    19471   647168    25639             0 mysqld
[448576.884553] [   4236]     0  4236     1218        0    49152      112             0 socat
[448576.884555] [   4237]     0  4237     1218        0    49152       97             0 socat
[448576.884556] [   4238]     0  4238     1133       59    49152       40             0 telldusd
[448576.884558] [   4253]     0  4253   325626      377   176128      130          -499 containerd-shim
[448576.884561] [   4270]     0  4270       49        0    32768        5             0 s6-svscan
[448576.884563] [   4342]     0  4342       49        0    32768        3             0 s6-supervise
[448576.884565] [   4467]     0  4467   325626      315   172032      147          -499 containerd-shim
[448576.884566] [   4507]     0  4507       49        0    32768        3             0 s6-svscan
[448576.884568] [   4686]     0  4686       49        0    32768        3             0 s6-supervise
[448576.884570] [   4895]     0  4895   268677        0   131072      155          -500 docker-proxy
[448576.884572] [   4957]     0  4957   325626      431   172032      137          -499 containerd-shim
[448576.884574] [   4989]     0  4989       49        0    36864        5             0 s6-svscan
[448576.884576] [   5167]     0  5167       49        0    32768        4             0 s6-supervise
[448576.884578] [   5313]     0  5313       49        0    32768        3             0 s6-supervise
[448576.884580] [   5314]     0  5314   169264        6  1486848     4616             0 node
[448576.884582] [   5601]     0  5601   325626      339   176128      170          -499 containerd-shim
[448576.884584] [   5624]     0  5624       49        0    32768        4             0 s6-svscan
[448576.884586] [   5652]     0  5652       49        0    32768        3             0 s6-supervise
[448576.884588] [   5653]     0  5653       49        0    32768        4             0 s6-supervise
[448576.884590] [   5654]     0  5654       49        0    32768        2             0 s6-supervise
[448576.884591] [   5655]     0  5655       49        0    32768        4             0 s6-supervise
[448576.884593] [   5656]     0  5656       49        0    32768        3             0 s6-supervise
[448576.884595] [   5657]     0  5657       49        0    32768        3             0 s6-supervise
[448576.884596] [   5659]     0  5659   240472     2377   512000     5174             0 deCONZ
[448576.884598] [   5660]     0  5660     1802        8    53248      490             0 bash
[448576.884604] [   5664]     0  5664     2615        6    61440      212             0 nginx
[448576.884606] [   5673]     0  5673    11903      153   126976     4872             0 websockify
[448576.884608] [   5777]     0  5777       49        0    28672        5             0 s6-supervise
[448576.884610] [   5796]     0  5796      596        1    45056       23             0 deCONZ-otau-dl.
[448576.884612] [   6069]     0  6069       49        0    32768        3             0 s6-supervise
[448576.884613] [   6070]     0  6070       49        0    32768        4             0 s6-supervise
[448576.884615] [   6072]     0  6072     1092        1    49152      124             0 sshd
[448576.884618] [   6073]     0  6073     5329        5    77824     4184             0 ttyd
[448576.884619] [   6147]     0  6147   110812      824   348160     5053             0 Xtigervnc
[448576.884621] [   6193]     0  6193     3985        7    65536     1702             0 tigervncserver
[448576.884623] [   6197]     0  6197      596        0    45056       21             0 Xvnc-session
[448576.884624] [   6201]     0  6201     6695        1    86016      200             0 vncconfig
[448576.884626] [   6202]     0  6202     4848       35    73728      203             0 x-window-manage
[448576.884627] [   6372]     0  6372     4848        1    73728      234             0 x-window-manage
[448576.884629] [   6585]     0  6585   152936        0  1478656     4828             0 node
[448576.884631] [   6880]     0  6880       49        0    32768        3             0 s6-supervise
[448576.884643] [   6882]     0  6882       49        0    32768        7             0 s6-supervise
[448576.884646] [   6883]     0  6883       49        0    32768        4             0 s6-supervise
[448576.884647] [   6884]     0  6884    11099        9   147456     7452             0 glances
[448576.884649] [   6887]     0  6887     1451        1    53248      196             0 nginx
[448576.884652] [   7167]     0  7167     1510        0    53248      254             0 nginx
[448576.884653] [   7169] 65534  7169     2741        0    61440      320             0 nginx
[448576.884655] [   7170]     0  7170   325626      393   180224      130          -499 containerd-shim
[448576.884657] [   7187]     0  7187       49        0    28672        4             0 s6-svscan
[448576.884659] [   7229]     0  7229       49        0    32768        3             0 s6-supervise
[448576.884661] [   7395]     0  7395       49        0    32768        3             0 s6-supervise
[448576.884663] [   7397]     0  7397   155954    26053  1224704    42925             0 python3
[448576.884664] [   7433]     0  7433     4366        1    69632      163             0 socat
[448576.884666] [   7434]     0  7434     4366        2    65536      162             0 socat
[448576.884668] [   7440]     0  7440     4366        8    65536      160             0 socat
[448576.884670] [   7442]     0  7442     1224        8    49152       93             0 socat
[448576.884672] [  34497]     0 34497     4294        1    77824      125             0 git
[448576.884674] [  51555]     0 51555     4293        1    69632      127             0 git
[448576.884676] [ 211758]     0 211758     1011        0    49152       21             0 sleep
[448576.884678] [ 211817]     0 211817     1011        0    45056       21             0 sleep
[448576.884680] [ 349878]     0 349878      394        0    45056       13             0 sleep
[448576.884683] [ 375536]     0 375536     1011        0    40960       22             0 sleep
[448576.884685] [ 378457]     0 378457      394        0    40960       12             0 sleep
[448576.884686] [ 379136]     0 379136   251901      356   131072        0          -499 runc
[448576.884688] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=6e1ac634595149d0e79b17d935600ab83bab460bbb70b44ce95624b45ef1c9d1,mems_allowed=0,global_oom,task_memcg=/docker/6e1ac634595149d0e79b17d935600ab83bab460bbb70b44ce95624b45ef1c9d1,task=mosquitto,pid=3455,uid=0
[448576.884702] Out of memory: Killed process 3455 (mosquitto) total-vm:6149216kB, anon-rss:5185120kB, file-rss:8kB, shmem-rss:0kB, UID:0 pgtables:12068kB oom_score_adj:0
[448577.221593] oom_reaper: reaped process 3455 (mosquitto), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

### LINKED ISSUE #1901: Mosquitto Broker error on startup
## The problem

On start up the add-on receive this error

[09:18:26] ERROR: Can't setup Home Assistant service mqtt

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue:  Current version: 5.1.1
- Last working add-on release (if known):  HA previus version 2021.2
- Operating environment (OS/Supervised):  Hass OS

## Problem-relevant configuration

When add-on start expose this error
[09:18:26] ERROR: Can't setup Home Assistant service mqtt

```yaml

```

## Traceback/Error logs

Only error on mosquitto broker add-on
[09:18:26] ERROR: Can't setup Home Assistant service mqtt
```txt

```

## Additional information
Nothing

### LINKED ISSUE #1934: Unable to start mosquitto addon
## The problem
[services.d] starting services
[services.d] done.
[22:18:43] ERROR: Requested resource /info was not found
[22:18:43] FATAL: Unknown log_level: 
[cmd] /run.sh exited 1

## Environment

- Add-on with the issue: mosquitto
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): supervisor-2021.03.6

## Problem-relevant configuration

It happens also with the default configuration.

## Traceback/Error logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:18:43] ERROR: Requested resource /info was not found
[22:18:43] FATAL: Unknown log_level: 
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### LINKED ISSUE #1956: Mosquitto addon
There are unexpected disconnects from clients. After disconnect client can't reconnect after some time (10min, sometimes 2h).

Home Assistant with HASSIO on terminal HP T610, 2GB RAM, SSD disc 128GB.
Proxmox.

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): don't know (i use only 5.1.1) 
- Operating environment (OS/Supervised): HomeAssistant HASSIO HP610, Proxmox

## Problem-relevant configuration

LOG with Docker connection:

> 1617054300: New client connected from 172.30.32.1 as 3JqAyLAkOcYcTP5f2sNsWu (p2, c1, k60, u'homeassistant').
> 1617054549: Socket error on client 3JqAyLAkOcYcTP5f2sNsWu, disconnecting.
> 1617054575: New connection from 172.30.32.1 on port 1883.
> 1617054575: New client connected from 172.30.32.1 as 7e2bOlP1LqPKmKaYchpVPr (p2, c1, k60, u'homeassistant').
> 1617054980: Saving in-memory database to /data/mosquitto.db.
> 1617056235: Socket error on client 7e2bOlP1LqPKmKaYchpVPr, disconnecting.

```

## Traceback/Error logs
<!--
  If you come across any trace or error logs, please provide them.
-->

```txt

```

### LINKED ISSUE #1984: Request to update Mosquitto addon to use Mosquitto 1.6+ or 2.0+ to support mqtt v5
## The problem

Request to update Mosquitto addon to use Mosquitto 1.6+ or 2.0+ to support mqtt v5.

Communicating over mqtt with HA it would be nice to be able to use v5 functionality, specifically the "no local / nl" setting to avoid echoing back messages sent.

## Environment

- Add-on with the issue: Mosquitto
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised):  Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

### PR DESCRIPTION
**Pull request by frenck**
# Changelog

## 6.0.0

- Support for anonymous logins has been removed
- Replaced Home Assistant authentication handling
- Merged local account handling with authentication plugin
- Add watchdog endpoint for health monitoring
- Updated mosquitto to 1.6.12
- Updated mosquitto auth plugin to 0.1.5
- Migrate add-on layout to S6 Overlay
- Migrate all script to use Bashio
- Update base image to Alpine Linux 3.13
- Add port descriptions

fixes #1887
fixes #1956
closes #1984
fixes #1817
fixes #1774
fixes #1747 (to extend possible for us)
fixes #1897 (no leaks in durance/load test found)
closes #1934
closes #729
fixes #1901
closes #1765 (Verified both local and HA users work and co-exist)

### CODE REVIEW

**Comment by thecode** [comment]
`.md` files looks ok, others are too complicated for me :-)

File: mosquitto/Dockerfile [hunk 1]
```diff
@@ -1,16 +1,16 @@
-ARG BUILD_FROM
+ARG BUILD_FROM=ghcr.io/home-assistant/amd64-base:3.13
```
Comment (pvizeli) [inline mosquitto/Dockerfile:1]: should be set from `build.json`

File: mosquitto/Dockerfile [hunk 2]
```diff
@@ -1,16 +1,16 @@
...
 FROM $BUILD_FROM
 
+# Set shell
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
```
Comment (pvizeli) [inline mosquitto/Dockerfile:5]: only comment: We can also set bash as the default on the base image. I think currently it's ash on alpine

File: mosquitto/rootfs/etc/cont-init.d/nginx.sh [hunk 3]
```diff
@@ -0,0 +1,9 @@
+#!/usr/bin/with-contenv bashio
+# ==============================================================================
+# Configures NGINX
+# ==============================================================================
+# This template only uses environment vars, no input
+echo "{}" \
+  | tempio \
+    -template /etc/nginx/nginx.gtpl \
```
Comment (pvizeli) [inline mosquitto/rootfs/etc/cont-init.d/nginx.sh:8]: We streamline that on all plugin + add-on to work with `/usr/share/tempio` to have all templates in one place like i.e. : https://github.com/home-assistant/addons/tree/master/homematic/rootfs/usr/share/tempio - I would like to keep that over the org as same

File: mosquitto/rootfs/etc/cont-init.d/mosquitto.sh [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+  anonymous "^$(bashio::config 'anonymous')" \
+  cafile "${cafile}" \
+  certfile "${certfile}" \
+  cutomize "^$(bashio::config 'customize.active')" \
+  cutomize_folder "$(bashio::config 'customize.folder')" \
+  keyfile "${keyfile}" \
+  require_certificate "^$(bashio::config 'require_certificate')" \
+  ssl "^${ssl}" \
+  | tempio \
+    -template /etc/mosquitto/mosquitto.gtpl \
```
Comment (pvizeli) [inline mosquitto/rootfs/etc/cont-init.d/mosquitto.sh:84]: dito

File: mosquitto/Dockerfile (hunk 1 above)
Comment (frenck) [reply mosquitto/Dockerfile:1]: It is, this is just for local building without passing anything. Will remove.

File: mosquitto/Dockerfile (hunk 2 above)
Comment (frenck) [reply mosquitto/Dockerfile:5]: Removing it

File: mosquitto/rootfs/etc/cont-init.d/mosquitto.sh [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+    cafile="${certfile}"
+  fi
+else
+  bashio::log.info "SSL is not enabled"
+  ssl="false"
+fi
+
+# Generate mosquitto configuration.
+bashio::var.json \
+  anonymous "^$(bashio::config 'anonymous')" \
```
Comment (ludeeus) [inline mosquitto/rootfs/etc/cont-init.d/mosquitto.sh:75]: This option has been removed https://github.com/home-assistant/addons/pull/2007/files#diff-848bc0f468357785581cda2e87e148761e451af03637596306b74b55147553efL21

**Review by ludeeus — APPROVED** [review]

**Review by pvizeli — APPROVED** [review]
